### ISSUE TITLE
Dashboard Migration

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/cow-dune#3]
A semi-comprehensive list of our current dashboards to be migrated into this repo:

- [x] https://dune.xyz/gnosis.protocol/GPv2-Solver-Info (#2)
- [ ] https://dune.xyz/gnosis.protocol/CowSwap
- [ ] https://dune.xyz/gnosis.protocol/Gnosis-Protocol-V2
- [ ] https://dune.xyz/gnosis.protocol/GP-Fees-and-Costs
- [ ] https://dune.xyz/gnosis.protocol/GP-Slippage
- [ ] https://dune.xyz/gnosis.protocol/GPv2-CoW-Explorer
- [ ] https://dune.xyz/gnosis.protocol/CoW-Referral-Data - This also needs to be auto-updated.
- [ ] https://dune.xyz/gnosis.protocol/GPv2-Trader-Surplus
- [ ] https://dune.xyz/gnosis.protocol/xdai-Trader-Data
