### ISSUE TITLE
Solver Alerts: Queries

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/cow-dune#7]
This task will layout the groundwork for a solver alert system. Putting in place the queries used to give high signal indication of "unusual" solver activity. Included in this first draft are the following:

The Mock Dashboard coming along as we go is the following:

- [] https://dune.com/gnosis.protocol/Solver-Alerts

and links to several other (more refined dashboards).

- [] https://dune.com/gnosis.protocol/Batch-Navigator
- [] https://dune.com/gnosis.protocol/CoW-Protocol-Personalized-Trade-History
- [] https://dune.com/gnosis.protocol/Failure-Rates-and-Cost-Coverage

The goal of this task will be to migrate all relevant dashboards into this project.
